### ISSUE TITLE
Additional notification for break

### ISSUE THREAD

**Issue by WindRayen** [tom-james-watson/breaktimer-app#80] opened 2020-11-26 05:06 UTC
Additional notification for break.
for example, notify at 60 min with simple popup and at 90 min with full screen.

Also, it would be nice to have start break now with full screen option, when using simple notification.

**Comment by tom-james-watson** [comment] 2020-11-26 10:09
Thanks for your suggestion. Closing as a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/80

**Comment by tom-james-watson** [comment] 2020-11-26 10:10
Of https://github.com/tom-james-watson/breaktimer-app/issues/77, sorry.

**Closed by tom-james-watson** 2020-11-26 10:09 UTC
