### ISSUE TITLE
Left clicking on the Windows 10 tray icon tries to rapidly open the menu multiple times

### ISSUE THREAD

**Issue by YiannisDermitzakis** [tom-james-watson/breaktimer-app#76] opened 2020-10-27 07:23 UTC
This is not a big deal, as right click opens the menu once, as expected, but it's confusing.

**Comment by YiannisDermitzakis** [comment] 2020-10-28 14:00
Update: Actually, sometimes it gets in an (infinite?) loop and the application crashes.

**Comment by tom-james-watson** [comment] 2020-10-28 14:18
What version of windows and of break timer?

**Comment by YiannisDermitzakis** [comment] 2020-11-06 10:43
Windows 10 Pro, Version 2004
BreakTimer 0.7.5

**Comment by tom-james-watson** [comment] 2020-11-08 15:36
Can you please try with version 0.7.6 which was released a few days ago. It upgraded Electron, which would be the kind of thing that would fix this. Thanks!

**Comment by YiannisDermitzakis** [comment] 2020-11-09 06:32
Yup, that was it. Thanks!

**Comment by YiannisDermitzakis** [comment] 2020-11-09 12:31
I guess it was premature of me to close the issue. After using the 0.7.6 for a while, it began demonstrating the same behavior.

**Comment by ozzi-** [comment] 2020-12-17 07:29
Win 10, 0.7.7 - freshly installed - can't reproduce

**Comment by WayneKoorts** [comment] 2020-12-21 21:02
Hi, I've just discovered BreakTimer and came to see if anyone else was experiencing this issue.  I'm on Windows 10, 0.7.7.  It doesn't happen right after the app opens, but I'll see if I can figure out how to reproduce it.

When it does happen, it ultimately ends up crashing the app.

**Comment by WayneKoorts** [comment] 2020-12-21 21:08
I've had the app running for about 5 minutes now and it's already starting to happen.  There seems to be some correlation between the timer logic and the number of times the menu opens.  If I had the time, I would look into the code myself, but at this stage I'd suggest looking at your assignment of events relating to the menu opening.  My gut feeling is there is a huge stack of duplicate menu open events piling up over time which then get fired all at the same time.

I've also noticed that the issue doesn't occur with right-clicks, only with left-clicks.

**Comment by WayneKoorts** [comment] 2020-12-21 22:22
Fast-forward about an hour and, as suspected, the delay has gotten progressively worse, but not to the point of crashing.  Right-click is still instant.  The last full crash I had was first thing this morning, after the app had been running for probably 20ish hours.

Anyway, hopefully this is enough info for someone to be able to investigate further at the code-level.  Happy to do further testing if required.

**Comment by tom-james-watson** [comment] 2020-12-22 09:47
OK - thanks for that info - that led me straight to the problem. This code:

https://github.com/tom-james-watson/breaktimer-app/blob/master/app/main/lib/tray.ts#L120-L122

Should be moved to just below

https://github.com/tom-james-watson/breaktimer-app/blob/master/app/main/lib/tray.ts#L29

so that we only ever register this click event once.

Till that change is made, the workaround is to use right click!

**Comment by tom-james-watson** [comment] 2021-01-01 11:35
Fixed in https://github.com/tom-james-watson/breaktimer-app/commit/20f314615757443ade10c6c08e3babcd71b957f8. Will be available in version 0.8.0 which is being published now.

**Closed by tom-james-watson** 2021-01-01 11:35 UTC
