### ISSUE TITLE
Break screen not on top of other apps

### ISSUE THREAD

**Issue by easpro** [tom-james-watson/breaktimer-app#57] opened 2020-06-30 11:40 UTC
If a break begins while using my PC's mouse, the break screen does not appear on top of other windows.  Rather, it appears behind other windows, making it impossible to know if a break has started.  I'm running Windows 10 Home, version 1909 and BreakTimer 0.7.3

**Comment by tom-james-watson** [comment] 2020-06-30 11:47
Thanks for your bug report.

I think this is a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/39. I'll add a note to that one that it can manifest in this way.

**Closed by tom-james-watson** 2020-06-30 11:47 UTC
