### ISSUE TITLE
[Feature_Request] Menu Bar Image version for Enable and Disable

### ISSUE THREAD

**Issue by nur-917Hub** [tom-james-watson/breaktimer-app#294] opened 2024-10-07 01:48 UTC
Currently we do not know either BreakTimer is enable or disable by seeing the menu bar image (unless we click on the menu bar image)

If possible to distinguish menu bar image for enable and disable version

**Comment by tom-james-watson** [comment] 2024-11-09 14:56
Duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/126

**Closed by tom-james-watson** 2024-11-09 14:56 UTC
