### ISSUE TITLE
Break Screen won't release, locks screen

### ISSUE THREAD

**Issue by rak-sj** [tom-james-watson/breaktimer-app#34] opened 2020-03-10 18:32 UTC
I have been a faithful user of Break Time for quite a while.
After uploading the most recent version (thinking it might take care of the java boot error popup),
after locking the screen for 2 mins, it would not release, and my keyboard and mouse were unresponsive.  This happened at least 3 times.
It was hard to get out of the lockscreen, but I was able to ctrl-alt-del and get to the task manager and kill the breaktimer executable so my screen was accessible again.
I had to "disable" breaktimer (which stopped the problem).
I am running:
Windows 10
ver 1909 (OS Build 18363.592)

I have always loved Break Timer (been using for quite a while now) and hope this can be fixed!
I miss using it!
Thanks!

**Comment by tom-james-watson** [comment] 2020-03-12 09:10
Closing as duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/34

**Closed by tom-james-watson** 2020-03-12 09:10 UTC
