### ISSUE TITLE
[Feature request] Long break

### ISSUE THREAD

**Issue by isle99** [tom-james-watson/breaktimer-app#105] opened 2021-07-21 09:19 UTC

**Comment by tom-james-watson** [comment] 2021-07-21 09:26
You'll need to provide a description of what you mean.

**Comment by tom-james-watson** [comment] 2021-07-21 09:26
Potentially a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/77.

**Comment by isle99** [comment] 2021-07-21 11:43
This would be similar to what a lot of pomodoro apps use. After X short breaks a long break is triggered with a different length.

This definitely could be integrated with issue #77. It's probably a much better idea to just let users decide what breaks they want.

**Comment by tom-james-watson** [comment] 2021-07-21 11:46
OK - closing as a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/77 then. Feel free to comment there if you don't feel like your request is represented by the current description.

**Closed by tom-james-watson** 2021-07-21 11:46 UTC
