### ISSUE TITLE
Countdown timer stuck in next break in less a minutes 

### ISSUE THREAD

**Issue by thomasTAT** [tom-james-watson/breaktimer-app#256] opened 2023-12-06 11:21 UTC
**Describe the bug**

Countdown timer stuck in next break in less a minutes and is not triggering the break. notification.

**Expected behavior**
 triggering the break

**Screenshots**
![image](https://github.com/tom-james-watson/breaktimer-app/assets/109513632/2010ca26-ab4f-4a29-971a-1f99f97ec162)

**Specs:**
 - OS version: [windows 11 23H2]

**Comment by tom-james-watson** [comment] 2023-12-06 13:17
Duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/206

**Closed by tom-james-watson** 2023-12-06 13:17 UTC
