### ISSUE TITLE
Working clock hours seem to be in UTC rather than local time

### ISSUE THREAD

**Issue by KeithMcClelland** [tom-james-watson/breaktimer-app#71] opened 2020-09-28 00:23 UTC
I set a wide window since I work from home but early evening in eastern North America was out of working hours. Turned the feature off and it started timing again.

**Comment by tom-james-watson** [comment] 2020-09-28 09:04
They should be local time. Sounds like a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/67

**Closed by tom-james-watson** 2020-09-28 09:04 UTC
