### ISSUE TITLE
Feature Request: Stop timer going off during videos calls

### ISSUE THREAD

**Issue by tandy-1000** [tom-james-watson/breaktimer-app#159] opened 2022-04-01 07:25 UTC
It would be useful if the timer wouldn't ring out during video calls, e.g. when using Zoom.

**Comment by tom-james-watson** [comment] 2022-06-04 11:36
Closing as duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/35

**Closed by tom-james-watson** 2022-06-04 11:36 UTC
