### ISSUE TITLE
[Feature Request] Pause Breaktimer during Screenshares

### ISSUE THREAD

**Issue by komplexb** [tom-james-watson/breaktimer-app#205] opened 2023-01-16 04:40 UTC
Great app, thanks for making it. 
It's one of the first things I install on a new OS.

Zoom and similar apps have a feature to hide notifications during screenshares. 
Is it possible to detect when a screenshare is active and pause Breaktimer whenever a screenshare is detected and re-enable when the share ends?

It'd be helpful for collaborative activities or presentations.

Thanks.

**Comment by tom-james-watson** [comment] 2023-01-17 10:08
Going to close as duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/35

**Closed by tom-james-watson** 2023-01-17 10:08 UTC
