### ISSUE TITLE
FEATURE REQUEST - Disable during Calls/Meetings on Microsoft Teams 

### ISSUE THREAD

**Issue by TheBreadNinja** [tom-james-watson/breaktimer-app#267] opened 2024-03-21 20:46 UTC
If Microsoft Teams is in a meeting/call then timer should be paused/disabled till meeting/call is closed.

**Comment by tom-james-watson** [comment] 2024-03-21 21:02
Duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/35

**Closed by tom-james-watson** 2024-03-21 21:02 UTC
