### ISSUE TITLE
[Feature Request] Disable breaks for 1 hour

### ISSUE THREAD

**Issue by TerryyyZhang** [tom-james-watson/breaktimer-app#183] opened 2022-09-29 16:06 UTC
An option can be shown in the menu bar just down the "Disable" and can disable breaks for a certain amount of time (e.g. 1 hour). 

This function would be very helpful for users who need to temporarily do things other than working (like watching Netflix), but intend to switch on Breaktimer later. Even though currently, users can already opt-in to skip breaks when they don't need them, many choose to opt-out of the skipping break function in the settings. This creates a problem because users will have to disable the breaks or quit the Breaktimer, and then they later forget to turn it on. They will only realized that when a long time has passed and no breaks are shown.

**Comment by tom-james-watson** [comment] 2022-09-29 17:37
Duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/13

**Closed by tom-james-watson** 2022-09-29 17:37 UTC
