### ISSUE TITLE
[Feature Request] Add an option to disable breaks for a specific amount of time

### ISSUE THREAD

**Issue by TheCheddarCheese** [tom-james-watson/breaktimer-app#278] opened 2024-06-10 16:50 UTC
Right now you can only disable them for good, and sometimes when I do that I forget to turn them back on. I think it would be nice if you could only disable them for say, 1 hour.

**Comment by tom-james-watson** [comment] 2024-06-10 17:31
Duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/13

**Closed by tom-james-watson** 2024-06-10 17:31 UTC
