### ISSUE TITLE
[Feature  Request] Notificate before break and disable for a certain time period

### ISSUE THREAD

**Issue by Jiang10086** [tom-james-watson/breaktimer-app#242] opened 2023-09-14 08:44 UTC
### Notificate before break
For example, the app can send notification via Windows Notification 20s before break starts, so I can be ready for the break.

### Disable for a certain time period
It will be helpful when I want to do a thing for a long time without being disturbed, such as watching movie. Now I can only simply disable it and forget to turn it on. So, if I can disable it for 2 hr or 30min or something, It will be wonderful.

After all, thanks for developing this app, that helps me a lot with eyes caring XD

**Comment by tom-james-watson** [comment] 2023-09-14 09:56
Sounds like a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/241

**Closed by tom-james-watson** 2023-09-14 09:56 UTC
