### ISSUE TITLE
[Feature Request] Pause break during system game mode

### ISSUE THREAD

**Issue by Savio-Sou** [tom-james-watson/breaktimer-app#271] opened 2024-04-02 22:27 UTC
Adding a toggle for auto-pausing breaks when system enters game mode would be nice.

### Alternative

Adding an application pause-list for auto-pausing breaks when certain applications are running would be equally great, if more achievable.

**Comment by tom-james-watson** [comment] 2024-04-03 06:46
This is a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/35

**Closed by tom-james-watson** 2024-04-03 06:46 UTC
