### ISSUE TITLE
Timer Ends but Break Doesn't Start

### ISSUE THREAD

**Issue by benpages** [tom-james-watson/breaktimer-app#279] opened 2024-06-16 08:30 UTC
**Describe the bug**
When I start working, the timer starts as planned. I can see the minutes being counted down. But it never goes to break. Instead, it shows "Next break in less than a minute" if I click on the BreatTimer icon in  the toolbar. The green popup never shows.

It's worked before and works sometimes (when restarting the computer or app). But now, more often than not, it gets stuck. 

Using MacOS 14.5 on MacBook Air with M1 chip.
![SCR-20240616-jpnq](https://github.com/tom-james-watson/breaktimer-app/assets/86982605/3ff916c4-89b5-4e17-b207-a4934d4ff9ed)
![SCR-20240616-jpln](https://github.com/tom-james-watson/breaktimer-app/assets/86982605/bb513970-3825-473f-b522-dbe3c2bee505)

**Comment by tom-james-watson** [comment] 2024-06-16 09:15
Duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/206

**Closed by tom-james-watson** 2024-06-16 09:15 UTC
